---
    - name: 'Elasticsearch - Add repo key'
      apt_key:
        url: "{{ repo_key }}"
        state: present

    - name: 'Elasticsearch - Add repo'
      apt_repository:
         repo: "{{ repo_url }}"
         state: present

    - name: 'Elasticsearch - Install package'
      apt:
        name: "{{ es_package }}"
        update_cache: true
        state: present
      notify:
        - Elasticsearch - restart service

    - name: 'Elasticsearch - Configure java path'
      replace:
        path: "{{ default_es_file }}"
        regexp: JAVA_HOME=$
        replace: "JAVA_HOME={{ java_path }}"
      notify:
        - Elasticsearch - restart service

    - name: 'Elasticseach - Configure service'
      service:
        name: "elasticsearch"
        enabled: yes
        state: started
      notify:
        - Elasticsearch - restart service
